### ISSUE TITLE
header is not define 

### ISSUE THREAD

**Issue by BipulRahi** [xenova/transformers.js#546] opened 2024-01-28 07:59 UTC
### Question

![image](https://github.com/xenova/transformers.js/assets/91903346/d14b8e30-1ed1-4840-ab83-7d2fda0871a0)

**Comment by BipulRahi** [comment] 2024-01-28 07:59
it shows header is not define

**Comment by xenova** [comment] 2024-01-28 08:59
Hi there 👋 This is most likely because you're using an outdated (and unsupported) version of Node.js (possibly v16). Please upgrade to at least v18.

Duplicate of https://github.com/xenova/transformers.js/issues/263

**Comment by BipulRahi** [comment] 2024-01-28 09:28
> Hi there 👋 This is most likely because you're using an outdated (and unsupported) version of Node.js (possibly v16). Please upgrade to at least v18.
> 
> Duplicate of #263

thx @xenova upgrading node works

**Closed** 2024-01-28 09:28 UTC
Labels: question
