### ISSUE TITLE
`aggregation_strategy` in TokenClassificationPipeline

### ISSUE THREAD

**Issue by boat-p** [xenova/transformers.js#648] opened 2024-03-15 04:07 UTC
### Question

Hello, from Transformers original version they have aggregation_strategy parameter to group the token corresponding to the same entity together in the predictions or not. But in transformers.js version I haven't found this parameter. Is it possible to provide this parameter? I want the prediction result as same as the original version.

**Comment by xenova** [comment] 2024-04-10 21:35
Duplicate of https://github.com/xenova/transformers.js/issues/648. Will answer there :)

**Closed by xenova** 2024-04-10 21:35 UTC
Labels: question
