### ISSUE TITLE
[Bug] ONNX shape error when using feature-extraction pipeline

### ISSUE THREAD

**Issue by mishig25** [xenova/transformers.js#355] opened 2023-10-12 14:46 UTC
**Describe the bug**
You get this onnx runtime error when you run the snippet below. 
```
/Users/runner/work/1/s/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 512 by 513
An error occurred during model execution: "Error: Non-zero status code returned while running Add node. Name:'/embeddings/Add_1' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 512 by 513
```

If I understand it correctly, [gte-small](https://huggingface.co/thenlper/gte-small) seq length is 512 tokens. However, the input I'm supplying becomes 512 tokens (which is bigger than 512 tokens). Since I'm using `pipeline`, I would expect the truncation to happen automatically in the tokenizer under the hood. But I guess that is not the case?

**How to reproduce**
```js
import { pipeline } from '@xenova/transformers';

let extractor = await pipeline('feature-extraction', 'Xenova/gte-small');
let input = "# 2024 Summer Olympics\n\n## The Games\\[edit\\]\n\n### Sports\\[edit\\]\n\nle\"><span>Image</span></span> Basketball<ul><li>Basketball <small>(2)</small></li><li>3×3 basketball <small>(2)</small></li></ul></li><li><span typeof=\"mw:File\"><span>Image</span></span> Boxing <small>(13)</small></li><li><span typeof=\"mw:File\"><span>Image</span></span> Breaking <small>(2)</small></li></ul></td><td><ul><li><span typeof=\"mw:File\"><span>Image</span></span> Canoeing<ul><li>Slalom <small>(6)</small></li><li>Sprint <small>(10)</small></li></ul></li><li><span typeof=\"mw:File\"><span>Image</span></span> Cycling<ul><li>BMX freestyle <small>(2)</small></li><li>BMX racing <small>(2)</small></li><li>Mountain biking <small>(2)</small></li><li>Road <small>(4)</small></li><li>Track <small>(12)</small></li></ul></li><li><span typeof=\"mw:File\"><span>Image</span></span> Equestrian<ul><li>Dressage <small>(2)</small></li><li>Eventing <small>(2)</small></li><li>Jumping <small>(2)</small></li></ul></li><li><span typeof=\"mw:File\"><span>Image</span><a"
let output = await extractor(input, { pooling: 'none', normalize: true });
```

**Expected behavior**

pipeline automatically performs truncation if necessary

**Environment**
- Transformers.js version: ^2.6.0
- Browser (if applicable): node v20.3.1    npm 9.6.7
- Operating system (if applicable): MacBook Pro Intel running macOS Ventura
- Other:

encountered the error during https://github.com/huggingface/chat-ui/pull/502

**Comment by xenova** [comment] 2023-10-13 01:23
By default, the tokenizer truncates to `model_max_length` which is specified in tokenizer_config.json. In this case, `gte-small` has a very large value for it, for some reason. https://huggingface.co/thenlper/gte-small/blob/c20abe89ac0cdf484944ebdc26ecaaa1bfc9cf89/tokenizer_config.json#L7

However, `max_position_embeddings` in [config.json](https://huggingface.co/thenlper/gte-small/blob/c20abe89ac0cdf484944ebdc26ecaaa1bfc9cf89/config.json#L13) is set to 512, and this should be used too. I'll fix that.

**Comment by mishig25** [comment] 2023-10-13 09:10
@xenova wdyt https://huggingface.co/Xenova/gte-small/discussions/1 ?

**Comment by xenova** [comment] 2023-10-14 06:44
Thanks @mishig25! Merged that for now, and I will soon make the fix for this too.

**Comment by xenova** [comment] 2023-11-04 16:02
While working on a simple fix for this, it's worth point out that the exact same problem occurs in the python library:
```py
from transformers import pipeline
pipe = pipeline('feature-extraction', 'thenlper/gte-small')
input = "# 2024 Summer Olympics\n\n## The Games\\[edit\\]\n\n### Sports\\[edit\\]\n\nle\"><span>Image</span></span> Basketball<ul><li>Basketball <small>(2)</small></li><li>3×3 basketball <small>(2)</small></li></ul></li><li><span typeof=\"mw:File\"><span>Image</span></span> Boxing <small>(13)</small></li><li><span typeof=\"mw:File\"><span>Image</span></span> Breaking <small>(2)</small></li></ul></td><td><ul><li><span typeof=\"mw:File\"><span>Image</span></span> Canoeing<ul><li>Slalom <small>(6)</small></li><li>Sprint <small>(10)</small></li></ul></li><li><span typeof=\"mw:File\"><span>Image</span></span> Cycling<ul><li>BMX freestyle <small>(2)</small></li><li>BMX racing <small>(2)</small></li><li>Mountain biking <small>(2)</small></li><li>Road <small>(4)</small></li><li>Track <small>(12)</small></li></ul></li><li><span typeof=\"mw:File\"><span>Image</span></span> Equestrian<ul><li>Dressage <small>(2)</small></li><li>Eventing <small>(2)</small></li><li>Jumping <small>(2)</small></li></ul></li><li><span typeof=\"mw:File\"><span>Image</span><a"
output = pipe(input)
```

results in
```py
RuntimeError: The size of tensor a (513) must match the size of tensor b (512) at non-singleton dimension 1
```

**Comment by devfacet** [comment] 2023-12-22 15:57
Also this one https://huggingface.co/Xenova/bge-small-en-v1.5/discussions/1

**Comment by xenova** [comment] 2023-12-22 15:57
@devfacet Done! Thanks 🤗

**Comment by xenova** [comment] 2024-01-27 17:58
Closing this since:
1. Transformers.js has the exact same behaviour as python library
2. The issue is due to a model/tokenizer configuration issue, which is something the model creator should be responsible for.

**Closed by xenova** 2024-01-27 17:58 UTC
Labels: bug
