### ISSUE TITLE
Example not working on Chrome/Arc v.124(M1 Mac)

### ISSUE THREAD

**Issue by justrach** [xenova/transformers.js#764] opened 2024-05-15 07:08 UTC
### System Info

M1 Mac
Sonoma
Using the example code.

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Using the repository from : https://github.com/xenova/transformers.js/tree/v3/examples/webgpu-chat and "@xenova/transformers": "github:xenova/transformers.js#v3", it gets stuck on ..loading model..

On the huggingface demo here is the output on the console: 
<img width="468" alt="image" src="https://github.com/xenova/transformers.js/assets/54503978/e5f31701-4fbc-4740-afb6-fa30d501bea3">

Meanwhile on the local page, here is how the output looks like:
<img width="792" alt="image" src="https://github.com/xenova/transformers.js/assets/54503978/477913cc-3f7b-4fea-868d-054fff172121">

### Reproduction

1. Clone repo from https://github.com/xenova/transformers.js/tree/v3/examples/webgpu-chat 
2. npm i and do npm run dev;
3. Go to url
4. Load Model
5. Model gets stuck on ...loading...

**Comment by xenova** [comment] 2024-05-15 11:27
Duplicate of https://github.com/xenova/transformers.js/issues/748.

**Comment by xenova** [comment] 2024-05-17 13:38
It should now work (commits: [here](https://github.com/xenova/transformers.js/commit/2c2c0871df4b899f7874d9e2ffc5fc61c7273e9b) and [here](https://github.com/xenova/transformers.js/commit/e32d4ebb6fe715e6634335123c07a96d0dc62ac8))!

**Closed by xenova** 2024-05-17 13:38 UTC
Labels: bug

**Comment by justrach** [comment] 2024-05-17 17:06
Thanks! Do you have a page where there's documentation on how to convert ONNX models to ONNX-Web models by any chance

**Comment by xenova** [comment] 2024-05-23 20:54
Sure, we use [Optimum](https://github.com/huggingface/optimum?tab=readme-ov-file#onnx--onnx-runtime), and you can find additional information there.

You can also use our helper [conversion script](https://github.com/xenova/transformers.js/blob/main/scripts/convert.py) for helping with quantization.

**Comment by justrach** [comment] 2024-05-25 07:28
> Sure, we use [Optimum](https://github.com/huggingface/optimum?tab=readme-ov-file#onnx--onnx-runtime), and you can find additional information there.
> 
> You can also use our helper [conversion script](https://github.com/xenova/transformers.js/blob/main/scripts/convert.py) for helping with quantization.

Thanks Joshua!
